import {useMemo,useState} from 'react';
import {useParams} from 'react-router-dom';
import {Play,RotateCcw,Save,Lightbulb,Settings2,CheckCircle2,Clock3,GitBranch} from 'lucide-react';
import {modules} from '../data/modules';
import {runScheduling,summarize} from '../algorithms/scheduling';
import {processLifecycle,pcbForProcess} from '../algorithms/processManagement';
import {threadLifecycle,tcbForThread} from '../algorithms/threads';
import {runSynchronization} from '../algorithms/synchronization';
const defaultScheduling='0 5\n1 3\n2 2\n3 4';
const defaultProcess='0 5 1\n1 3 2\n2 2 3\n3 4 1';
const defaultThreads='T1 User 4\nT2 Kernel 3\nT3 User 2';
const defaultSync='P1 3\nP2 2\nP3 4\nP4 2';
export default function Simulator(){
 const {moduleId}=useParams(); const m=modules.find(x=>x.id===moduleId)||modules[0];
 const scheduling=moduleId==='cpu-scheduling', process=moduleId==='process', threads=moduleId==='threads', sync=moduleId==='synchronization';
 const [name,setName]=useState(m.name+' experiment'),[algorithm,setAlgorithm]=useState(m.algorithms[0]),[input,setInput]=useState(scheduling?defaultScheduling:process?defaultProcess:threads?defaultThreads:sync?defaultSync:''),[quantum,setQuantum]=useState(1),[result,setResult]=useState(null),[saved,setSaved]=useState(false);
 const metrics=useMemo(()=>result&&!result.demo&&!process?summarize(result):null,[result,process]);
 function run(){if(scheduling)setResult(runScheduling(algorithm,input,Number(quantum)||2));else if(process)setResult(processLifecycle(input));else if(threads)setResult(threadLifecycle(input,Number(quantum)||1));else if(sync)setResult(runSynchronization(algorithm,input));else setResult({demo:true,rows:[],timeline:[]});}
 function reset(){setInput(scheduling?defaultScheduling:process?defaultProcess:threads?defaultThreads:'');setResult(null);setSaved(false);}
 function save(){if(!result)return;const item={id:Date.now(),name,module:m.name,moduleId,algorithm,createdAt:new Date().toISOString(),result};const old=JSON.parse(localStorage.getItem('osExperiments')||'[]');localStorage.setItem('osExperiments',JSON.stringify([item,...old].slice(0,50)));setSaved(true);}
 const processList=process&&result?.rows?.length?result.rows:[];
 return <div className='page'><div className='sim-header'><div><span className='kicker'>{m.topic}</span><h2>{m.name}</h2><p>{m.description}</p></div><div className='sim-actions'><button className='btn secondary' onClick={save} disabled={!result}><Save size={16}/>{saved?'Saved':'Save'}</button><button className='btn primary' onClick={run}><Play size={16}/> Run simulation</button></div></div>
 <div className='sim-layout'><section className='panel'><div className='panel-title'><span><Settings2 size={17}/> Experiment setup</span></div><label>Experiment name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Algorithm<select value={algorithm} onChange={e=>setAlgorithm(e.target.value)}>{m.algorithms.map(a=><option key={a}>{a}</option>)}</select></label>{scheduling&&<label>Time quantum<input type='number' min='1' value={quantum} onChange={e=>setQuantum(e.target.value)}/></label>}<label>Input data<textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={scheduling?'Arrival Time Burst Time [Priority]\n0 5\n1 3\n2 2':process?'Arrival Time Burst Time Priority\n0 5 1\n1 3 2':'Enter experiment input here...'}/></label><button className='btn primary full-btn' onClick={run}><Play size={16}/> Run experiment</button><button className='reset' onClick={reset}><RotateCcw size={15}/> Reset</button></section>
 <section className='panel visualization'><div className='panel-title'><span>Live visualization</span><span className={result?'live':'muted'}>{result?'● Complete':'● Ready'}</span></div>{result?.timeline?.length&&!process&&!threads&&!sync?<><div className='gantt'>{result.timeline.map((t,i)=><div className='gantt-item' key={i} style={{flexGrow:Math.max(1,t.end-t.start)}}><b>{t.id}</b><small>{t.start}–{t.end}</small></div>)}</div><div className='metric-grid'><Metric icon={Clock3} label='Avg waiting' value={metrics.avgWaiting}/><Metric icon={CheckCircle2} label='Avg turnaround' value={metrics.avgTurnaround}/><Metric icon={Clock3} label='Avg response' value={metrics.avgResponse}/></div><div className='result-table'><div className='table-row head'><span>Process</span><span>Completion</span><span>Waiting</span><span>Turnaround</span></div>{result.rows.map(p=><div className='table-row' key={p.id}><span>{p.id}</span><span>{p.completion}</span><span>{p.waiting}</span><span>{p.turnaround}</span></div>)}</div></>:result?.timeline?.length&&process?<ProcessVisualization result={result} processes={processList}/>:result?.timeline?.length&&threads?<ThreadVisualization result={result}/>:result?.timeline?.length&&sync?<SynchronizationVisualization result={result}/>:result?.demo?<div className='empty-state'><div className='empty-icon'><CheckCircle2 size={28}/></div><h3>Experiment workspace ready</h3><p>The UI flow is ready. The dedicated algorithm engine for <strong>{m.name}</strong> will be implemented module-by-module.</p></div>:<div className='empty-state'><div className='empty-icon'><Play size={28}/></div><h3>Your simulation will appear here</h3><p>Enter your experiment data and run the simulation to watch the OS behavior step by step.</p></div>}</section></div>
 <section className='explain'><Lightbulb size={21}/><div><b>Learning insight</b><p>{result?.timeline?.length&&process?'A process moves through Created → Ready → Running → Terminated. Context switching represents the OS changing the CPU from one process to another.':result?.timeline?.length&&threads?'Threads share the CPU while keeping their own execution state. Compare User and Kernel threads and observe how context switches divide CPU time.':result?.timeline?.length&&sync?'Synchronization coordinates processes around shared resources. Observe lock acquisition, waiting, release, and buffer behavior.':result?.timeline?.length?'The '+algorithm+' scheduler executed '+result.rows.length+' processes. Compare waiting and turnaround times to understand the scheduling trade-offs.':'Run the experiment to see the execution flow and understand what the Operating System is doing.'}</p></div></section></div>;
}
function ProcessVisualization({result,processes}){const active=processes[0];const pcb=pcbForProcess(active);return <div className='process-viz'><div className='process-flow'>{['Created','Ready','Running','Waiting','Terminated'].map((state,i)=><div className={'process-state '+(i<3||state==='Terminated'?'reached':'')} key={state}><span>{i+1}</span><b>{state}</b></div>)}</div><div className='process-timeline'>{result.timeline.map(t=><div className='gantt-item' key={t.id} style={{flexGrow:Math.max(1,t.end-t.start)}}><b>{t.id}</b><small>{t.start}–{t.end}</small></div>)}</div><div className='pcb-card'><div className='panel-title'><span><GitBranch size={17}/> Process Control Block</span></div><div className='pcb-grid'><span>PID<strong>{pcb.pid}</strong></span><span>State<strong>{pcb.state}</strong></span><span>Program Counter<strong>{pcb.programCounter}</strong></span><span>Registers<strong>{pcb.registers}</strong></span><span>Arrival Time<strong>{pcb.arrivalTime}</strong></span><span>CPU Burst<strong>{pcb.cpuBurst}</strong></span></div></div><div className='result-table'><div className='table-row head'><span>Process</span><span>Arrival</span><span>Completion</span><span>Waiting</span></div>{processes.map(p=><div className='table-row' key={p.id}><span>{p.id}</span><span>{p.arrival}</span><span>{p.completion}</span><span>{p.waiting}</span></div>)}</div></div>}
function ThreadVisualization({result}){const active=result.rows[0];const tcb=tcbForThread(active);return <div className='thread-viz'><div className='thread-summary'><span>{result.threadCount} threads</span><span>{result.contextSwitches} context switches</span><span>{result.totalTime} CPU time</span></div><div className='process-timeline'>{result.timeline.map((t,i)=><div className='gantt-item thread-item' key={i} style={{flexGrow:Math.max(1,t.end-t.start)}}><b>{t.id}</b><small>{t.type} · {t.start}–{t.end}</small></div>)}</div><div className='thread-states'>{result.rows.map(t=><div className='thread-card' key={t.id}><b>{t.id}</b><span className={'thread-badge '+t.type.toLowerCase()}>{t.type} thread</span><small>Terminated · burst {t.burst}</small></div>)}</div><div className='pcb-card'><div className='panel-title'><span><GitBranch size={17}/> Thread Control Block</span></div><div className='pcb-grid'><span>TID<strong>{tcb.tid}</strong></span><span>Type<strong>{tcb.type}</strong></span><span>State<strong>{tcb.state}</strong></span><span>Program Counter<strong>{tcb.programCounter}</strong></span><span>Registers<strong>{tcb.registers}</strong></span><span>CPU Burst<strong>{tcb.cpuBurst}</strong></span></div></div><div className='result-table'><div className='table-row head'><span>Thread</span><span>Type</span><span>Completion</span><span>Context switches</span></div>{result.rows.map(t=><div className='table-row' key={t.id}><span>{t.id}</span><span>{t.type}</span><span>{t.completion}</span><span>{t.contextSwitches}</span></div>)}</div></div>}
function SynchronizationVisualization({result}){return <div className='sync-viz'><div className='thread-summary'><span>{result.mode}</span><span>{result.totalTime} time units</span>{result.capacity&&<span>Capacity {result.capacity}</span>}</div><div className='process-timeline'>{result.timeline.map((t,i)=><div className='gantt-item sync-item' key={i} style={{flexGrow:Math.max(1,t.end-t.start)}}><b>{t.id}</b><small>{t.state||t.action} · {t.start}–{t.end}</small></div>)}</div><div className='sync-events'>{result.events.map((e,i)=><div className='sync-event' key={i}><span>{e.time}</span><b>{e.type}</b><small>{e.id||'Buffer'}</small></div>)}</div><div className='result-table'><div className='table-row head'><span>Process</span><span>Action</span><span>Time</span><span>Details</span></div>{result.rows.map((row,i)=><div className='table-row' key={i}><span>{row.id}</span><span>{row.action||result.mode}</span><span>{row.time??row.start}</span><span>{row.bufferSize??row.burst}</span></div>)}</div></div>}
function Metric({icon:Icon,label,value}){return <div className='metric'><Icon size={17}/><span>{label}</span><strong>{value}</strong></div>}
