import {useMemo,useState} from 'react';
import {useParams} from 'react-router-dom';
import {Play,RotateCcw,Save,Lightbulb,Settings2,CheckCircle2,Clock3} from 'lucide-react';
import {modules} from '../data/modules';
import {runScheduling,summarize} from '../algorithms/scheduling';
const defaultInput='0 5\n1 3\n2 2\n3 4';
export default function Simulator(){
 const {moduleId}=useParams();const m=modules.find(x=>x.id===moduleId)||modules[0];const scheduling=moduleId==='cpu-scheduling';
 const [name,setName]=useState(m.name+' experiment'),[algorithm,setAlgorithm]=useState(m.algorithms[0]),[input,setInput]=useState(scheduling?defaultInput:''),[quantum,setQuantum]=useState(2),[result,setResult]=useState(null),[saved,setSaved]=useState(false);
 const metrics=useMemo(()=>result&&!result.demo?summarize(result):null,[result]);
 function run(){if(scheduling)setResult(runScheduling(algorithm,input,Number(quantum)||2));else setResult({demo:true,rows:[],timeline:[]});}
 function reset(){setInput(scheduling?defaultInput:'');setResult(null);setSaved(false);}
 function save(){if(!result)return;const item={id:Date.now(),name,module:m.name,moduleId,algorithm,createdAt:new Date().toISOString(),result};const old=JSON.parse(localStorage.getItem('osExperiments')||'[]');localStorage.setItem('osExperiments',JSON.stringify([item,...old].slice(0,50)));setSaved(true);}
 return <div className="page"><div className="sim-header"><div><span className="kicker">{m.topic}</span><h2>{m.name}</h2><p>{m.description}</p></div><div className="sim-actions"><button className="btn secondary" onClick={save} disabled={!result}><Save size={16}/>{saved?'Saved':'Save'}</button><button className="btn primary" onClick={run}><Play size={16}/> Run simulation</button></div></div>
 <div className="sim-layout"><section className="panel"><div className="panel-title"><span><Settings2 size={17}/> Experiment setup</span></div><label>Experiment name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Algorithm<select value={algorithm} onChange={e=>setAlgorithm(e.target.value)}>{m.algorithms.map(a=><option key={a}>{a}</option>)}</select></label>{scheduling&&<label>Time quantum<input type="number" min="1" value={quantum} onChange={e=>setQuantum(e.target.value)}/></label>}<label>Input data<textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={scheduling?'Arrival Time Burst Time [Priority]\n0 5\n1 3\n2 2':'Enter experiment input here...'}/></label><button className="btn primary full-btn" onClick={run}><Play size={16}/> Run experiment</button><button className="reset" onClick={reset}><RotateCcw size={15}/> Reset</button></section>
 <section className="panel visualization"><div className="panel-title"><span>Live visualization</span><span className={result?'live':'muted'}>{result?'● Complete':'● Ready'}</span></div>{result?.timeline?.length?<><div className="gantt">{result.timeline.map((t,i)=><div className="gantt-item" key={i} style={{flexGrow:Math.max(1,t.end-t.start)}}><b>{t.id}</b><small>{t.start}–{t.end}</small></div>)}</div><div className="metric-grid"><Metric icon={Clock3} label="Avg waiting" value={metrics.avgWaiting}/><Metric icon={CheckCircle2} label="Avg turnaround" value={metrics.avgTurnaround}/><Metric icon={Clock3} label="Avg response" value={metrics.avgResponse}/></div><div className="result-table"><div className="table-row head"><span>Process</span><span>Completion</span><span>Waiting</span><span>Turnaround</span></div>{result.rows.map(p=><div className="table-row" key={p.id}><span>{p.id}</span><span>{p.completion}</span><span>{p.waiting}</span><span>{p.turnaround}</span></div>)}</div></>:result?.demo?<div className="empty-state"><div className="empty-icon"><CheckCircle2 size={28}/></div><h3>Experiment workspace ready</h3><p>The UI flow is ready. The dedicated algorithm engine for <strong>{m.name}</strong> will be implemented module-by-module.</p></div>:<div className="empty-state"><div className="empty-icon"><Play size={28}/></div><h3>Your simulation will appear here</h3><p>Enter your experiment data and run the simulation to watch the OS behavior step by step.</p></div>}</section></div>
 <section className="explain"><Lightbulb size={21}/><div><b>Learning insight</b><p>{result?.timeline?.length?'The '+algorithm+' scheduler executed '+result.rows.length+' processes. Compare waiting and turnaround times to understand the scheduling trade-offs.':'Run the experiment to see the execution flow and understand what the Operating System is doing.'}</p></div></section></div>;
}
function Metric({icon:Icon,label,value}){return <div className="metric"><Icon size={17}/><span>{label}</span><strong>{value}</strong></div>}
